### ISSUE TITLE
I just tried to run run.sh. There was an error.

### ISSUE THREAD

**Issue by mikemikemikecai** [caelum/mamute#126]
[vagrant@localhost scripts]$ ./run.sh
Exception in thread "main" java.lang.NoClassDefFoundError: br/com/caelum/vraptor/server/Main
Caused by: java.lang.ClassNotFoundException: br.com.caelum.vraptor.server.Main
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: br.com.caelum.vraptor.server.Main. Program will exit.

[vagrant@localhost mamute]$ java -version
java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (rhel-1.13.5.1.el6_6-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

[vagrant@localhost mamute]$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.5.40 MySQL Community Server (GPL) by Remi

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| test               |
+--------------------+
2 rows in set (0.01 sec)

mysql>

**Comment by leocwolter** [comment]
Since we got no answer, I'm closing the issue. Please tell us if you are still stuck
