### ISSUE TITLE
Removing question throws exception if the user go to karma history

### ISSUE THREAD

**Issue by khajavi** [caelum/mamute#216]
step to recreate this issue:
1. remove one question
2. go to http://127.0.0.1:8080/users/1002/milad
3. now the Mamute throw this exception:

```java
Error 500
java.lang.NullPointerException
	at org.mamute.dto.KarmaByContextHistory.(KarmaByContextHistory.java:19)
	at org.mamute.dao.ReputationEventDAO.karmaByContext(ReputationEventDAO.java:79)
	at org.mamute.dao.ReputationEventDAO.karmaWonByQuestion(ReputationEventDAO.java:57)
	at org.mamute.controllers.UserProfileController.showProfile(UserProfileController.java:70)
	at org.mamute.controllers.UserProfileController$Proxy$_$$_WeldClientProxy.showProfile(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by csokol** [comment]
Closed by #207
