### ISSUE TITLE
Recently merged PR #222 causing problem with embedded Jetty?

### ISSUE THREAD

**Issue by JamesSullivan** [caelum/mamute#226]
When running Mamute on Ubuntu 14.04/Java 8 with embedded Jetty I am now seeing the error below. I suspect it is due to the recently merged pull request Preliminary Tomcat 8 compatibility #222 [1](https://github.com/caelum/mamute/pull/222) 

Jetty 8 	   Servlet 3.0
Tomcat 8    Servlet 3.1

16:49:24  WARN [Holder              ] 
java.lang.ClassNotFoundException: org.apache.catalina.servlets.DefaultServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:415)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:92)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:71)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:92)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:291)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:776)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:258)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1213)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:699)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:454)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:224)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at br.com.caelum.vraptor.server.VRaptorServer.start(VRaptorServer.java:41)
	at br.com.caelum.vraptor.server.Main.main(Main.java:17)

**Comment by JamesSullivan** [comment]
If I remove lines 36 -60 in web.xml embedded Jetty works fine.  
https://github.com/xdarklight/mamute/commit/71f14756c8576172c48123d6017dbfc67ee24799

**Comment by xdarklight** [comment]
thanks for reporting, it seems that I didn't look at the error log.
I'm going to come up with a different solution.
