### ISSUE TITLE
PostgreSQL support *PLEASE*

### ISSUE THREAD

**Issue by Tux** [caelum/mamute#246]
As for many (obviously) MySQL is not an option, please make switching to PostgreSQL easy.

As mamute already uses hibernate, that shouldn't be too difficult.

I rewrote the mysql dump to postgresql syntax using the attached perl script
[conv.zip](https://github.com/caelum/mamute/files/189398/conv.zip)
 and created the database, then modified hibernate config to use postgres drivers, installed the postgres driver and ran run.sh to hit:

```
1:09:54  INFO [RAMJobStore         ] RAMJobStore initialized.
11:09:54  INFO [QuartzScheduler     ] Scheduler meta-data: Quartz Scheduler (v2.1.5) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

11:09:54  INFO [StdSchedulerFactory ] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
11:09:54  INFO [StdSchedulerFactory ] Quartz scheduler version: 2.1.5
11:09:54  INFO [SessionFactoryCreator] Loading hibernate xml from file:/data/mamute/WEB-INF/classes/development/hibernate.cfg.xml
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
11:09:56  WARN [SqlExceptionHelper  ] SQL Error: 0, SQLState: 42601
11:09:56 ERROR [SqlExceptionHelper  ] ERROR: syntax error at or near "("
  Position: 55
11:09:56  INFO [MigrationRunner     ] Couldnt prepare tables: org.hibernate.exception.SQLGrammarException: could not execute statement
11:09:56  INFO [MigrationRunner     ] >>>> org.hibernate.exception.SQLGrammarException: could not execute statement
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
```
at which point I need to delve into the sources
[conv.zip](https://github.com/caelum/mamute/files/189395/conv.zip)

**Comment by felipeweb** [comment]
Hi @Tux, Do you want send a PR?

The `Migration Runner` use native SQL query.

to operate in the two databases you need to rewrite the migrations queries using ANSI SQL

**Comment by Tux** [comment]
I was working on a new branch "postgresql", but I keep running into blockades, so I gave up for now

**Comment by xdarklight** [comment]
there's more than "just" the "Migration Runner", see #37
