### ISSUE TITLE
1.4 (2016-03-23) fails on java7

### ISSUE THREAD

**Issue by Tux** [caelum/mamute#248]
Started from scratch with a git checkout and a MySQL database
```
commit 3e7c18d9cdf2d9f010f32539a913d2666e54addc
Merge: 5395418 eb21345
Author: Felipe Oliveira <felipeweb.programador@gmail.com>
Date:   Wed Mar 23 11:53:31 2016 -0300
```

```
mvn -U clean compile install
```
Build passes
I copied WEB-INF/ over to my test environment
I altered development/hibernate.cfg.xml to connect to the correct database with the correct user/pass
I altered the date format from dd/MM/yyyy to dd-MM-yyyy
I created the database.
```
$ sh run.sh
:
17:16:39  WARN [ServletHandler      ] /
javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.jsp.JspTagException: "items" in &lt;forTokens&gt must be an instance of java.lang.String or an instance of javax.el.ValueExpression that evaluates to a java.lang.String;
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:944)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:879)
```
```
Linux 4.5.0-1-default [openSUSE Tumbleweed (20160321)] x86_64
$ java -version
java version "1.7.0_91"
Java(TM) SE Runtime Environment (build 1.7.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.91-b03, mixed mode)
$ mysql --version
mysql  Ver 15.1 Distrib 10.0.22-MariaDB, for Linux (x86_64) using readline 5.2
$  mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/java/maven
Java version: 1.7.0_91, vendor: Oracle Corporation
Java home: /usr/lib64/jvm/jdk1.7.0_91/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.5.0-1-default", arch: "amd64", family: "unix"
```

**Comment by felipeweb** [comment]
@Tux  i can't reproduce this with master branch.
try run command without `-U` and check if your `assets` dir is ok, when i run with `-U` the grunt task broke my assets dir

**Comment by Tux** [comment]
Sorry for the long pastes …
```
mamute-git > git reset --hard
mamute-git > rm -rf src/main/webapp/assets
mamute-git > git ls-files | grep -i assets | xargs git checkout
mamute-git > mvn clean compile
:
:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.211 s
[INFO] Finished at: 2016-03-30T12:29:45+02:00
[INFO] Final Memory: 42M/350M
[INFO] ------------------------------------------------------------------------
mamute-git > mvn install
:
:
Results :

Tests run: 294, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- grunt-maven-plugin:1.4.1:npm (default) @ mamute ---
[INFO] OS Name: Linux
npm WARN mamute@1.0.0 No repository field.
npm WARN mamute@1.0.0 No license field.
[INFO]
[INFO] --- grunt-maven-plugin:1.4.1:grunt (default) @ mamute ---
[INFO] OS Name: Linux
Initializing
Command-line options: --no-color, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-clean/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-less" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-less/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-less/package.json...OK
Loading "less.js" tasks...OK
+ less

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-watch/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-concat/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-cssmin/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-cssmin/package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-contrib-copy/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-filerev" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-filerev/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-filerev/package.json...OK
Loading "filerev.js" tasks...OK
+ filerev

Registering "grunt-usemin" local Npm module tasks.
Reading /pro/3gl/mamute-git/node_modules/grunt-usemin/package.json...OK
Parsing /pro/3gl/mamute-git/node_modules/grunt-usemin/package.json...OK
Loading "usemin.js" tasks...OK
+ usemin, useminPrepare
Loading "Gruntfile.js" tasks...OK
+ build, default, remapFilerev, run

Running tasks: build

Running "build" task

Running "default" task

Running "clean:before" (clean) task
Verifying property clean.before exists in config...OK
Files: src/main/webapp/css/, src/main/webapp/font/, src/main/webapp/imgs/, src/main/webapp/js/ -> before
Options: force=false, no-write=false
ERROR
Warning: Cannot delete files outside the current working directory. Use --force to continue.

Aborted due to warnings.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:24 min
[INFO] Finished at: 2016-03-30T12:32:18+02:00
[INFO] Final Memory: 47M/609M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.allegro:grunt-maven-plugin:1.4.1:grunt (default) on project mamute: Unable to execute mojo: Command execution failed. Process exited with an error: 6 (Exit value: 6) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
```
$ npm install
npm WARN mamute@1.0.0 No repository field.
npm WARN mamute@1.0.0 No license field.
```

```
$ rsync -avHl src/main/webapp/WEB-INF/ /data/mamute-1.4/WEB-INF/ --delete
:
:
$ cd /data/mamute-1.4
-- correct user/pass in WEB-INF/classes/development/hibernate.cfg.xml
$ sh run.sh
:
:
13:10:58  INFO [DefaultAdminCreator ] =========================
Hibernate: update LoginMethod set serviceEmail=?, token=?, type=?, user_id=? where id=?
13:10:58  INFO [VRaptor             ] VRaptor 4.1.2 successfuly initialized
13:10:58  INFO [AbstractConnector   ] Started SelectChannelConnector@sv05:8080
13:11:16  INFO [QuartzConfigurator  ] Invoking quartz configurator at http://localhost:8080/jobs/configure
13:12:29  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
13:12:29  INFO [HttpMethodDirector  ] Retrying request
13:12:29  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
13:12:29  INFO [HttpMethodDirector  ] Retrying request
13:12:29  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
13:12:29  INFO [HttpMethodDirector  ] Retrying request
13:12:29 ERROR [QuartzConfigurator  ] Could not configure quartz!
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:344)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:280)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at br.com.caelum.vraptor.quartzjob.QuartzConfigurator$StartQuartz.run(QuartzConfigurator.java:77)
        at java.lang.Thread.run(Thread.java:745)
:
```
Not bad so far, but access localserver:8080 I get http://tux.nl/Files/20160330131627.png → looks like the css gone missing

When I sign up as a new user, the page redirects to localhost:8080 instead of localserver:8080

Working my way through …

**Comment by Tux** [comment]
After also rsync'ing css and imgs mamute runs!
Now I need the feedback of the user who requested this :)
Thanks for support so far

**Comment by xdarklight** [comment]
latest mamute (git master) works fine for me on one of our servers running Ubuntu Server with OpenJDK 7u95
so I cannot reproduce this problem

**Comment by Tux** [comment]
I've got 1.4 up and running now.
